#!/usr/bin/env python
# -*- coding: utf-8 -*-
import json
import os
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

base = Path(os.path.dirname(os.path.abspath(__file__)))

env = Environment(
    loader=FileSystemLoader(base / "templates"),
    autoescape=select_autoescape(["cpp"]),
)

with open(base / "interface.json", "r") as f:
    data = json.load(f)

template = env.get_template("driver.cpp")
result = template.render(spec=data)
with open(base.parent / "celerite2" / "driver.cpp", "w") as f:
    f.write("// NOTE: This file was autogenerated\n")
    f.write("// NOTE: Changes should be made to the template\n\n")
    f.write(result)
